#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

char* generate_cmake(const char* project, int c_standard, int include_dir,
			const char* executable_name)
{
	char* last_cmake = strdup(
		"# This CMakeLists.txt was auto-generated by cinit.\n"
		"# To build, you can run cmake --build .. or, if a Makefile has been generated, run that.\n"
		"cmake_minimum_required(VERSION 3.13)\n");


	/* write project() */
	int def_len = snprintf(NULL, 0, 
			"%s\nproject(%s C)\n",
			last_cmake, project);

	char* buf = malloc(def_len + 1);
	if (!buf) 
		exit(1);

	snprintf(buf, def_len + 1, 
			"%s\nproject(%s C)\n",
			last_cmake, project);

	if (last_cmake != 
			"# This CMakeLists.txt was auto-generated by cinit.\n"
			"# To build, you can run cmake --build .. or, if a Makefile has been generated, run that.\n\n"
			"cmake_minimum_required(VERSION 3.13)\n") {
		free(last_cmake);
	}
	last_cmake = buf;


	/* write set(CMAKE_C_STANDARD %d) */
	if (c_standard != -1){
		int len = snprintf(NULL, 0, 
				"%s\n# defines\nset(CMAKE_C_STANDARD %d)\n",
				last_cmake, c_standard);

		char* buffer = malloc(len + 1);
		if (!buffer) 
			exit(1);

		snprintf(buffer, len + 1, 
				"%s\n# defines\nset(CMAKE_C_STANDARD %d)\n",
				last_cmake, c_standard);

		if (last_cmake != 
				"# This CMakeLists.txt was auto-generated by cinit.\n"
				"# To build, you can run cmake --build .. or, if a Makefile has been generated, run that.\n\n"
				"cmake_minimum_required(VERSION 3.13)\n") {
			free(last_cmake);
		}
		last_cmake = buffer;
	}

	/* write include_directories(include) */
	if (include_dir == 1){
		int len = snprintf(NULL, 0, 
				"%s\ninclude_directories(include)\n",
				last_cmake);

		char* buffer = malloc(len + 1);

		snprintf(buffer, len + 1, 
				"%s\ninclude_directories(include)\n",
				last_cmake);

		free(last_cmake);
		last_cmake = buffer;
	}


	/* write 
	 * file(GLOB_RECURSE SRC_FILES src/*.c)
	 * add_executable(%s ${SRC_FILES}) */
	int len = snprintf(NULL, 0, 
			"%s\nfile(GLOB_RECURSE SRC_FILES src/*.c)\nadd_executable(%s ${SRC_FILES})",
			last_cmake, executable_name);

	char* buffer = malloc(len + 1);

	snprintf(buffer, len + 1, 
			"%s\nfile(GLOB_RECURSE SRC_FILES src/*.c)\nadd_executable(%s ${SRC_FILES})",
			last_cmake, executable_name);

	free(last_cmake);
	last_cmake = buffer;

	return last_cmake;

}


